name: Build and deploy Azure templates

on: 
  workflow_call:
    inputs:
      AZURE_LOCATION: 
        type: string
        description: 'Azure region name'
        required: true
        default: 'australiaeast'
      AZURE_SUBSCRIPTION_ID:
        type: string
        description: 'Azure subscription id'
        required: true
    outputs:
      AZURE_KEYVAULT_NAME:
        description: 'Key Vault name'
        value: ${{ jobs.validate_and_deploy.outputs.AZURE_KEYVAULT_NAME }}

env:
  BICEP_FILE_PATH: './azure/templates'
  BICEP_FILE_NAME: 'main'
  BICEP_OUTPUT_DIRECTORY: './azure/templates/builds'

jobs:
  validate_and_deploy:
    runs-on: ubuntu-latest 
    outputs:
      AZURE_KEYVAULT_NAME: ${{ steps.azureResources.outputs.NXFUTIL_AZ_KV_NAME }} 
    steps:
    # Inputs
    - name: 'Show inputs'
      run: |
        echo AZURE_LOCATION : ${{ inputs.AZURE_LOCATION }}
        echo AZURE_SUBSCRIPTION_ID : ${{ inputs.AZURE_SUBSCRIPTION_ID }}

    # Variables
    - name: 'Show variables'
      run: |
        echo BICEP_FILE_PATH : ${{ env.BICEP_FILE_PATH }}       
        echo BICEP_FILE_NAME : ${{ env.BICEP_FILE_NAME }}       
        echo BICEP_OUTPUT_DIRECTORY : ${{ env.BICEP_OUTPUT_DIRECTORY }}       

    # Login
    - name: 'Azure login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Checkout
    - name: 'Checkout repository branch'
      uses: actions/checkout@v1

    # Get objectId from clientId
    - name: 'Get principal from clientId'
      id: gitHubMsiPrincipal
      run: |
        az ad sp list --spn "$CLIENT_ID"
        objectId=$(az ad sp list --spn "$CLIENT_ID" --query "[].id" --output tsv)
        echo objectId is $objectId
        echo "::set-output name=objectId::$objectId"
      env: 
        CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}

    # Build
    - name: Azure CLI - Validate Bicep file ${{ env.BICEP_FILE_PATH }}/${{ env.BICEP_FILE_NAME }}.bicep
      uses: Azure/cli@1.0.4
      with:
        inlineScript: |
          mkdir -p ${{ env.BICEP_OUTPUT_DIRECTORY }}
          az deployment sub validate --name ${{ github.run_number }} --location ${{ inputs.AZURE_LOCATION }} --subscription ${{ inputs.AZURE_SUBSCRIPTION_ID }} --template-file ${{ env.BICEP_FILE_PATH }}/${{ env.BICEP_FILE_NAME }}.bicep --parameters gitHubMsiClientId=${{ steps.gitHubMsiPrincipal.outputs.objectId }}
          az bicep upgrade 
          az bicep build --file ${{ env.BICEP_FILE_PATH }}/${{ env.BICEP_FILE_NAME }}.bicep --outdir ${{ env.BICEP_OUTPUT_DIRECTORY }}
    
    # Deployment
    - name: Deploy infrastructure
      id: azureResources
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ inputs.AZURE_SUBSCRIPTION_ID }}
        region: ${{ inputs.AZURE_LOCATION }} 
        deploymentName: ${{ github.run_number }}
        template: ${{ env.BICEP_OUTPUT_DIRECTORY }}/${{ env.BICEP_FILE_NAME }}.json
        parameters: gitHubMsiClientId=${{ steps.gitHubMsiPrincipal.outputs.objectId }}

    # Outputs
    - name: 'Show outputs'
      run: |
        echo AZURE_KEYVAULT_NAME : ${{ steps.azureResources.outputs.NXFUTIL_AZ_KV_NAME }}

    # Logout
    - name: 'Azure logout'
      run: |
        az logout
      if: always()