name: Build and publish Rust functions

on:
  workflow_call:
    inputs:
      AZURE_FUNCTIONAPP_NAME: 
        type: string
        description: 'Azure Function App name'
        required: true

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'azure/functions/rust'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    # Inputs
    - name: 'Show inputs'
      run: |
        echo AZURE_FUNCTIONAPP_NAME : ${{ inputs.AZURE_FUNCTIONAPP_NAME }}

    # Variables
    - name: 'Show variables'
      run: |
        echo AZURE_FUNCTIONAPP_PACKAGE_PATH : ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} 

    # Checkout
    - name: 'Checkout repository branch'
      uses: actions/checkout@v2   

    # Login
    - name: 'Azure login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}   

    # Cache
    - name: 'Cache cargo target dir'
      id: cache
      uses: actions/cache@v3
      with:
        path: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/target'
        key: cargo-cache-nxfutil-target 

    # Install SSL
    - name: 'Install openssl dev binaries'
      shell: bash
      run: |
        sudo apt-get install pkg-config libssl-dev

    # Update rust tool chain
    - name: 'Update rust'
      uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: stable
          override: true

    # pushd to build dir 
    - name: 'pushd to build dir'
      shell: bash
      run: |
        pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'

    # Run cargo check
    - name: 'Run cargo check'
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --verbose

    # Run cargo build
    - name: 'Run cargo build'
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --verbose
   
    # Move files 
    - name: 'Select only required files for FuncApp'
      shell: bash
      run: |
        mkdir -p ./output/nxfutil
        cp -v ./nxfutil/function.json ./output/nxfutil/function.json
        cp -v ./target/release/handler ./output/handler
        cp -v ./host.json ./output/host.json
        cp -v ./.funcignore ./output/.funcignore
        
    # popd
    - name: 'popd'
      shell: bash
      run: |
        popd

    # Deployment
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ inputs.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output

    # Logout
    - name: 'Azure logout'
      run: |
        az logout
      if: always()        