# Authentication
# Set up the following secrets in your GitHub repository: 
#
#   AZURE_CREDENTIALS
#
# For details on usage of secrets, please refer to:
#  https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

name: Main CICD

on: 
  workflow_dispatch:
    inputs:
      AZURE_LOCATION: 
        type: string
        description: 'Azure region name'
        required: true
        default: 'australiaeast'
      AZURE_SUBSCRIPTION_ID:
        type: string
        description: 'Azure subscription id'
        required: true
  push:
    branches:    
      - 'main'  

jobs: 
  azureTemplates:
    uses: axgonz/azure-nextflow/.github/workflows/azure-templates.yml@main
    with:
      AZURE_LOCATION: ${{ github.event.inputs.AZURE_LOCATION }}
      AZURE_SUBSCRIPTION_ID: ${{ github.event.inputs.AZURE_SUBSCRIPTION_ID }}
    secrets: inherit

  marshalOutputs:
    runs-on: ubuntu-latest
    needs: azureTemplates
    steps:
      - name: marshalOutputs
        id: marshalOutputs
        run: |
          kvName=${{ needs.azureTemplates.outputs.AZURE_KEYVAULT_NAME }}
          echo "::set-output name=AZURE_KEYVAULT_NAME::$kvName"
    outputs:
      AZURE_KEYVAULT_NAME: ${{ steps.azureResources.outputs.AZURE_KEYVAULT_NAME }}  

  showOutputs:
    runs-on: ubuntu-latest
    needs: marshalOutputs
    steps:
      - name: showOutputs
        id: showOutputs
        run: |
          echo ${{ needs.marshalOutputs.outputs.AZURE_KEYVAULT_NAME }}
  
  dockerImages:
    needs: marshalOutputs
    uses: axgonz/azure-nextflow/.github/workflows/docker-images.yml@main
    with:
      AZURE_KEYVAULT_NAME: ${{ needs.marshalOutputs.outputs.AZURE_KEYVAULT_NAME }}
    secrets: inherit