# Authentication
# Set up the following secrets in your GitHub repository: 
#
#   AZURE_CREDENTIALS
#
# For details on usage of secrets, please refer to:
#  https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

name: GitHub Workflows

on: 
  workflow_dispatch:
    inputs:
      AZURE_LOCATION: 
        type: string
        description: 'Azure region name'
        required: true
        default: 'australiaeast'
      AZURE_SUBSCRIPTION_ID:
        type: string
        description: 'Azure subscription id'
        required: true
      AZURE_RESOURCEGROUP_NAME:
        type: string
        description: 'Azure resource group name'
        required: true  

jobs:      
  azureTemplates:
    uses: axgonz/azure-nextflow/.github/workflows/azure-templates.yml@main
    with:
      AZURE_LOCATION: ${{ inputs.AZURE_LOCATION }}
      AZURE_SUBSCRIPTION_ID: ${{ inputs.AZURE_SUBSCRIPTION_ID }}
      AZURE_RESOURCEGROUP_NAME: ${{ inputs.AZURE_RESOURCEGROUP_NAME }}
    secrets: inherit

  dockerImages:
    needs: azureTemplates
    uses: axgonz/azure-nextflow/.github/workflows/docker-images.yml@main
    with:
      AZURE_KEYVAULT_NAME: ${{ needs.azureTemplates.outputs.AZURE_KEYVAULT_NAME }}
    secrets: inherit

  azureFunctions:
    needs: azureTemplates
    uses: axgonz/azure-nextflow/.github/workflows/azure-functions.yml@main
    with:
      AZURE_FUNCTIONAPP_NAME: ${{ needs.azureTemplates.outputs.AZURE_FUNCTIONAPP_NAME }}
    secrets: inherit    