# Authentication
# Set up the following secrets in your GitHub repository: 
#
#   AZURE_CONTAINERREGISTRY_PASSWORD
#
# For details on usage of secrets, please refer to:
#  https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

name: Build and push Docker images

on:
  workflow_dispatch:
    inputs:
      AZURE_CONTAINERREGISTRY_NAME: 
        description: 'Azure Container Registry name'
        required: true

env:
  AZURE_CONTAINERREGISTRY_NAME: ${{ github.event.inputs.AZURE_CONTAINERREGISTRY_NAME }}
  DOCKER_IMAGES_PATH: './docker/images'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository branch'
        uses: actions/checkout@v2
      
      - name: 'Login to Container Registry'
        uses: azure/docker-login@v1
        with:
          login-server: '${{ env.AZURE_CONTAINERREGISTRY_NAME }}.azurecr.io'
          username: ${{ env.AZURE_CONTAINERREGISTRY_NAME }}
          password: ${{ secrets.AZURE_CONTAINERREGISTRY_PASSWORD }}

      - name: 'Build and push images'
        shell: bash
        run: |
          pushd './${{ env.DOCKER_IMAGES_PATH }}'
          
          pushd ubuntu
          docker build -f Dockerfile . -t ${{ env.AZURE_CONTAINERREGISTRY_NAME }}.azurecr.io/default/ubuntu:${{ github.sha }}
          docker push ${{ env.AZURE_CONTAINERREGISTRY_NAME }}.azurecr.io/default/ubuntu:${{ github.sha }}
          popd

          pushd nextflow
          docker build -f Dockerfile . -t ${{ env.AZURE_CONTAINERREGISTRY_NAME }}.azurecr.io/default/nextflow:${{ github.sha }}
          docker push ${{ env.AZURE_CONTAINERREGISTRY_NAME }}.azurecr.io/default/nextflow:${{ github.sha }}
          popd

          popd