name: Build and archive rust binary - nxfutild

permissions:
      id-token: write
      contents: read

on:
  workflow_dispatch:

env:
  BIN_NAME: 'nxfutild'
  SOURCE_PATH: 'nxfutil/rust/nxfutild'
  RUST_BACKTRACE: 'full'
  CARGO_TARGET: 'x86_64-unknown-linux-gnu'
  
jobs:
  validate_and_push:
    runs-on: ubuntu-latest
    steps:
    # Variables
    - name: 'Show variables'
      run: |
        echo BIN_NAME : ${{ env.BIN_NAME }} 
        echo SOURCE_PATH : ${{ env.SOURCE_PATH }} 

    # Checkout
    - name: 'Checkout repository branch'
      uses: actions/checkout@v2                 
    
    # Update / Install Rust
    - name: 'Update / install rust'
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        target: ${{ env.CARGO_TARGET }}
        toolchain: stable
        default: true
        override: true

    # Cache
    - name: 'Cache cargo target dir'
      id: cache_nxfutil
      uses: actions/cache@v3
      with:
        path: '${{ env.SOURCE_PATH }}/target'
        key: 'cargo-target-${{ env.BIN_NAME }}'

    # Build
    - name: 'Build binary'
      shell: bash
      run: |       
        pushd '${{ env.SOURCE_PATH }}'
        cargo build --target "${{ env.CARGO_TARGET }}" --release
        popd

    # Archive
    - name: Archive binary
      uses: actions/upload-artifact@v3
      with:
        name: '${{ env.BIN_NAME }}'
        path: '${{ env.SOURCE_PATH }}/target/${{ env.CARGO_TARGET }}/release/${{ env.BIN_NAME }}'